# Final Assessment

Laura Dahm - i6235448

## 1. Introduction

Research question: How did the covid vaccinations influence the number of hospitalizations in Germany compared to other countries in the European Union?

## 2. Data preparation

In [2]:
# import relevant libraries:
import pandas as pd
import altair as alt
import ipywidgets as widgets

In [3]:
# load dataset:
covid = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')

In [4]:
covid

       iso_code  ... excess_mortality_cumulative_per_million
0           AFG  ...                                     NaN
1           AFG  ...                                     NaN
2           AFG  ...                                     NaN
3           AFG  ...                                     NaN
4           AFG  ...                                     NaN
...         ...  ...                                     ...
158625      ZWE  ...                                     NaN
158626      ZWE  ...                                     NaN
158627      ZWE  ...                                     NaN
158628      ZWE  ...                                     NaN
158629      ZWE  ...                                     NaN

[158630 rows x 67 columns]

## 3. Exploring and cleaning data

## 4. Descriptives and visualizations

## 5. Conclusion