# Final Assessment

Laura Dahm (i6235448)

## 1. Introduction

Research question: 

How high was the case fatality rate associated with covid-19 in Germany compared to other countries of the European Union in January 2022?

## 2. Data preparation

In [75]:
import pandas as pd
import altair as alt
import ipywidgets as widgets

In [76]:
covid = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')

After importing the relevant libraries and loading the dataset I first calculated the case fatality rate and then I selected the rows and columns relevant for my research question.

(case_fatality_rate = new_deaths_smoothed_per_million / new_cases_smoothed_per_million * 100)

In [77]:
covid['case_fatality_rate'] = covid['new_deaths_smoothed_per_million'] / covid['new_cases_smoothed_per_million'] * 100
relevant_columns = ['continent', 'location', 'date', 'new_cases_smoothed_per_million', 'new_deaths_smoothed_per_million', 'case_fatality_rate']
europe = covid.loc[covid.continent == 'Europe', relevant_columns]
covid_europe = europe.loc[covid.date.str.contains('2022-01-')]
covid_europe

       continent location  ... new_deaths_smoothed_per_million  case_fatality_rate
2111      Europe  Albania  ...                           1.392            1.043768
2112      Europe  Albania  ...                           1.293            0.818733
2113      Europe  Albania  ...                           1.293            0.818733
2114      Europe  Albania  ...                           0.845            0.463161
2115      Europe  Albania  ...                           0.597            0.384561
...          ...      ...  ...                             ...                 ...
154846    Europe  Vatican  ...                             NaN                 NaN
154847    Europe  Vatican  ...                             NaN                 NaN
154848    Europe  Vatican  ...                             NaN                 NaN
154849    Europe  Vatican  ...                             NaN                 NaN
154850    Europe  Vatican  ...                             NaN                 NaN

[1580 rows x 6 columns]

## 3. Exploring and cleaning data

First, I grouped the data by location and used descriptive statistics to get an overview of the values for each country and to see whether there are typos or missing data.

In [78]:
covid_europe.groupby('location').describe()

                       new_cases_smoothed_per_million  ... case_fatality_rate
                                                count  ...                max
location                                               ...
Albania                                          31.0  ...           1.043768
Andorra                                          31.0  ...           0.101123
Austria                                          31.0  ...           0.634287
Belarus                                          31.0  ...           1.656271
Belgium                                          31.0  ...           0.270686
Bosnia and Herzegovina                           31.0  ...           4.285334
Bulgaria                                         31.0  ...           3.181424
Croatia                                          31.0  ...           1.064302
Cyprus                                           31.0  ...           0.325987
Czechia                                          31.0  ...           1.357775
Denmark                                          31.0  ...           0.087816
Estonia                                          31.0  ...           0.517554
Faeroe Islands                                   31.0  ...           0.180844
Finland                                          31.0  ...           0.266417
France                                           31.0  ...           0.118380
Germany                                          31.0  ...           0.910169
Gibraltar                                        31.0  ...           0.098712
Greece                                           31.0  ...           0.585959
Guernsey                                          0.0  ...                NaN
Hungary                                          31.0  ...           4.605719
Iceland                                          31.0  ...           0.059212
Ireland                                          31.0  ...           0.206981
Isle of Man                                      31.0  ...           0.258716
Italy                                            31.0  ...           0.267160
Jersey                                            0.0  ...                NaN
Kosovo                                           31.0  ...           0.978414
Latvia                                           31.0  ...           1.468062
Liechtenstein                                    31.0  ...           0.727285
Lithuania                                        31.0  ...           1.261407
Luxembourg                                       31.0  ...           0.167231
Malta                                            31.0  ...           1.350624
Moldova                                          31.0  ...           4.613011
Monaco                                           31.0  ...           1.041724
Montenegro                                       31.0  ...           0.693071
Netherlands                                      31.0  ...           0.256956
North Macedonia                                  31.0  ...           2.939143
Norway                                           31.0  ...           0.197660
Poland                                           31.0  ...           4.236683
Portugal                                         31.0  ...           0.086313
Romania                                          31.0  ...           3.058387
Russia                                           31.0  ...           4.917674
San Marino                                       31.0  ...           0.537629
Serbia                                           31.0  ...           1.492656
Slovakia                                         31.0  ...           1.873011
Slovenia                                         31.0  ...           0.600505
Spain                                            31.0  ...           0.180931
Sweden                                           31.0  ...           0.108557
Switzerland                                      31.0  ...           0.153942
Ukraine                                          31.0  ...           5.053811
United Kingdom                                   30.0  ...           0.300694
Vatican                                          31.0  ...                NaN

[51 rows x 24 columns]

While I did not detect any typos, I saw that for some countries the data is incomplete (NaN).

I decided to delete all rows with missing data.

In [79]:
ce = covid_europe.dropna()
ce

       continent  ... case_fatality_rate
2111      Europe  ...           1.043768
2112      Europe  ...           0.818733
2113      Europe  ...           0.818733
2114      Europe  ...           0.463161
2115      Europe  ...           0.384561
...          ...  ...                ...
150816    Europe  ...           0.284446
150817    Europe  ...           0.290329
150818    Europe  ...           0.291733
150819    Europe  ...           0.293115
150820    Europe  ...           0.300694

[1487 rows x 6 columns]

After deleting the rows with missing data, I wanted to see which countries had data for every day of January 2022 which is why I looked at the value counts for the countries.

In [80]:
ce['location'].value_counts()

Albania                   31
Andorra                   31
Lithuania                 31
Luxembourg                31
Malta                     31
Moldova                   31
Monaco                    31
Montenegro                31
Netherlands               31
North Macedonia           31
Norway                    31
Poland                    31
Portugal                  31
Romania                   31
Russia                    31
San Marino                31
Serbia                    31
Slovakia                  31
Slovenia                  31
Spain                     31
Sweden                    31
Switzerland               31
Ukraine                   31
Liechtenstein             31
Latvia                    31
Kosovo                    31
Estonia                   31
Austria                   31
Belarus                   31
Belgium                   31
Bosnia and Herzegovina    31
Bulgaria                  31
Croatia                   31
Cyprus                    31
Czechia                   31
Denmark                   31
Faeroe Islands            31
Italy                     31
Finland                   31
France                    31
Germany                   31
Gibraltar                 31
Greece                    31
Hungary                   31
Iceland                   31
Ireland                   31
Isle of Man               31
United Kingdom            30
Name: location, dtype: int64

While most countries have values for all 31 days of January 2022, the UK, did not which is why I decided to exclude this country. 
(I only want to include countries with complete data.)

In [83]:
ce = ce[ce['location'].str.contains('United Kingdom') == False]
ce

       continent location  ... new_deaths_smoothed_per_million  case_fatality_rate
2111      Europe  Albania  ...                           1.392            1.043768
2112      Europe  Albania  ...                           1.293            0.818733
2113      Europe  Albania  ...                           1.293            0.818733
2114      Europe  Albania  ...                           0.845            0.463161
2115      Europe  Albania  ...                           0.597            0.384561
...          ...      ...  ...                             ...                 ...
149343    Europe  Ukraine  ...                           3.264            0.659196
149344    Europe  Ukraine  ...                           3.234            0.595354
149345    Europe  Ukraine  ...                           3.277            0.552301
149346    Europe  Ukraine  ...                           3.293            0.527369
149347    Europe  Ukraine  ...                           3.316            0.505580

[1457 rows x 6 columns]

## 4. Descriptives and visualizations

In order to describe the population, I grouped the data by location (country) and used descriptive statistics.

In [85]:
ce.groupby('location').agg(
    {
        'new_cases_smoothed_per_million':['min', 'max', 'mean', 'skew'],
        'new_deaths_smoothed_per_million':['min', 'max', 'mean', 'skew'],
        'case_fatality_rate':['min', 'max', 'mean', 'skew'],
    })

                       new_cases_smoothed_per_million  ... case_fatality_rate
                                                  min  ...               skew
location                                               ...
Albania                                       133.363  ...           2.316485
Andorra                                      1826.482  ...           0.152450
Austria                                       306.328  ...           1.673157
Belarus                                        97.912  ...          -0.473162
Belgium                                       825.679  ...           1.962875
Bosnia and Herzegovina                        139.423  ...           1.425477
Bulgaria                                      296.251  ...           1.286305
Croatia                                       960.254  ...           1.325199
Cyprus                                       1711.725  ...           0.902127
Czechia                                       479.594  ...           0.577386
Denmark                                      2800.621  ...           0.372360
Estonia                                       645.407  ...           1.676980
Faeroe Islands                               2254.122  ...           0.965050
Finland                                       674.433  ...           0.229796
France                                       2339.069  ...           1.049020
Germany                                       334.883  ...           0.613663
Gibraltar                                    2764.621  ...           5.567764
Greece                                       1718.116  ...          -0.016727
Hungary                                       251.501  ...           1.358890
Iceland                                      1925.979  ...           0.835545
Ireland                                       678.807  ...           0.708865
Isle of Man                                   429.859  ...           1.135595
Italy                                        1525.202  ...           0.634045
Kosovo                                         16.353  ...           3.293577
Latvia                                        427.745  ...           1.028873
Liechtenstein                                1012.032  ...           0.925415
Lithuania                                     581.018  ...           1.043616
Luxembourg                                   1076.356  ...           0.336545
Malta                                         455.615  ...           0.305223
Moldova                                        73.700  ...           1.380528
Monaco                                        347.021  ...           1.188587
Montenegro                                   1337.244  ...           0.818803
Netherlands                                   796.246  ...           1.773487
North Macedonia                               172.787  ...           1.780623
Norway                                        634.929  ...           1.115704
Poland                                        289.755  ...           0.099378
Portugal                                     1923.177  ...          -0.375472
Romania                                        59.345  ...           2.102322
Russia                                        109.080  ...          -0.252727
San Marino                                   2839.501  ...          -0.225061
Serbia                                        238.166  ...           2.128399
Slovakia                                      502.453  ...          -0.592600
Slovenia                                      709.570  ...           1.656145
Spain                                        1762.558  ...           0.744123
Sweden                                        583.104  ...           0.571961
Switzerland                                  1724.679  ...           1.483534
Ukraine                                        91.939  ...           0.277332

[47 rows x 12 columns]

In the interactive table below, you can select any member of the European Union to see the new cases, new deaths and case fatality rate for every day of January 2022.

In [87]:
from ipywidgets import interact
from ipywidgets import fixed

In [ ]:
def select_country_data(location, df):
  return df.loc[df['location'] == location, ]

In [89]:
interact(select_country_data, location = ['Germany', 'Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'], df = fixed(ce))

interactive(children=(Dropdown(description='location', options=('Germany', 'Austria', 'Belgium', 'Bulgaria', '…

In the interactive chart below, you can select any member of the European Union to see the case fatality rate (%) for every day of January 2022.

In [90]:
def select_country_data_chart(location, df):
  return df.loc[df['location'] == location, ]

In [ ]:
def visualize_country_data_chart(location, df):
  visualized_data = select_country_data_chart(location, df)
  
  lineplot = alt.Chart(visualized_data).mark_line().encode(
    x='date:O',
    y='case_fatality_rate:Q',
    color='location:N'
  )

  display(lineplot)

In [92]:
interact(visualize_country_data_chart, location = ['Germany', 'Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'], df = fixed(ce))

interactive(children=(Dropdown(description='location', options=('Germany', 'Austria', 'Belgium', 'Bulgaria', '…

## 5. Conclusion

Germany started the new year (01.01.2022) with a case fatality rate of about 0.9% which continuously decreased until it reached about 0.1% at the end of January 2022. 

Similar curves with overall lower case fatality rates can be seen in Austria, Belgium, Estonia, Netherlands and Slovenia. 
Similar curves with overall higher case fatality rates can be seen in Bulgaria, Czechia, Hungary, Latvia, Lithuania and Romania.

Curves with case fatality rates that are increasing throughout January 2022 can be seen in Spain.

The remaining countries of the European Union show (inverse) u-shaped, s-shaped or zigzag-patterned curves.